#!/bin/sh /etc/rc.common
USE_PROCD=1

# Service file for OpenWrt. Put in /etc/init.d/stalky and run:
# $ /etc/init.d/stalky enable
# $ /etc/init.d/stalky start

start_service() {
	procd_open_instance stalky
	procd_set_param command /root/stalky/fetcher.py
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param file /root/stalky/config.py
	procd_set_param netdev dev
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param user root
	procd_set_param pidfile /var/run/stalky.pid
	procd_close_instance
}

stop_service() {
	return 0
}
